name: klasifikasi_felidae
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_glass_morphism: ^1.0.0
  dotted_border: ^2.1.0
  carousel_slider: ^5.1.1
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  tflite_web: ^0.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/drawSplash1/
    - assets/drawSplash2/
    - assets/drawSplash3/